server:
  port: 8084
spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://postgres:5432/paymentdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
app:
  security:
    jwt-secret: ${JWT_SECRET:}
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
